---
- name: Copy over docker composes
  hosts: all
  become: true
  tasks:
    - name: Ensure 'render' group exists
      group:
        name: render
        state: present
        system: yes

    - name: Ensure 'koen' user is in 'render' group
      user:
        name: koen
        groups: render
        append: yes

    - name: Ensure /home/koen/arr-stack folder exists
      ansible.builtin.file:
        path: /home/koen/arr-stack
        state: directory
        owner: koen
        group: koen
        mode: '0755'

    - name: Copy over *arr stack compose file
      copy:
        src: ../docker/arr-stack/compose.yaml
        dest: /home/koen/arr-stack/compose.yaml
        owner: koen
        group: koen
        mode: '0644'

    - name: Ensure /home/koen/authentik folder exists
      ansible.builtin.file:
        path: /home/koen/authentik
        state: directory
        owner: koen
        group: koen
        mode: '0755'

    - name: Copy over Authentik compose file
      copy:
        src: ../docker/authentik/compose.yaml
        dest: /home/koen/authentik/compose.yaml
        owner: koen
        group: koen
        mode: '0644'

    - name: Docker Compose Up Arr-stack
      ansible.builtin.shell:
        cmd: cd /home/koen/arr-stack && docker compose up -d
      become: true
      become_user: koen

    - name: Docker Compose Up Authentik
      ansible.builtin.shell:
        cmd: cd /home/koen/authentik && docker compose up -d
      become: true
      become_user: koen