---
- name: Set up NGINX web server with custom index.html
  hosts: all
  become: true
  tasks:

    # - name: Install NGINX
    #   apt:
    #     name: nginx
    #     state: present
    #     update_cache: yes

    # - name: Ensure NGINX is running and enabled
    #   service:
    #     name: nginx
    #     state: started
    #     enabled: yes

    - name: Deploy html dir
      copy:
        src: ../nginx/html/
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Deploy sites-available
      copy:
        src: ../nginx/etc/nginx/sites-available/
        dest: /etc/nginx/sites-available/
        owner: root
        group: root
        mode: '0644'
        follow: no

    - name: Validate NGINX config
      ansible.builtin.shell:
        cmd: sudo nginx -t
      become: true
      become_user: koen

    - name: Reload NGINX
      ansible.builtin.shell:
        cmd: cd /etc/nginx/sites-enabled/ && sudo systemctl reload nginx
      become: true
      become_user: koen